name: Deployment
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: eu-west-1
      - uses: actions/checkout@v1
        with:
          repository: AltaPay/plugin-infrastructure
          token: '${{ secrets.ACCESS_TOKEN }}'
          ref: origin/prestashop
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.4
      - name: Terraform Init
        run: terraform init
        working-directory: ../plugin-infrastructure/provision/plugins
      - name: Terraform workspace
        run: terraform workspace select prestashop
        working-directory: ../plugin-infrastructure/provision/plugins
      - name: Terraform Plan
        run: terraform plan
        working-directory: ../plugin-infrastructure/provision/plugins
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ../plugin-infrastructure/provision/plugins
      - name: Sleep for 20 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: 20s
      - name: Set env TEST_BRANCH_NAME
        run: "if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then\n    echo \"TEST_BRANCH_NAME=${{ github.head_ref }}\" >> \"$GITHUB_ENV\"\nelse\n    echo \"TEST_BRANCH_NAME=master\" >> \"$GITHUB_ENV\"\nfi  \t\n"
      - name: Set env PRESTASHOP_VERSION
        run: |
          echo "PRESTASHOP_VERSION=1.6.1.24" >> "$GITHUB_ENV"
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: prestashop.yml
          directory: ../plugin-infrastructure/deploy/plugins
          key: '${{secrets.SSHKEY}}'
          options: >
            -u ubuntu

            -i inventory

            --extra-vars "branch_name=altapay-config gatewayURL=${{
            secrets.GATEWAYURL }} gatewayUser=${{ secrets.GATEWAYUSER }}
            gatewayPass=${{ secrets.GATEWAYPASS }}
            prestashop_version=${{env.PRESTASHOP_VERSION}}"   
      - name: Export IP
        run: |
          testvar=$(sed '4!d' inventory)
          echo $testvar
          echo "IP=$testvar">> $GITHUB_ENV
        working-directory: ../plugin-infrastructure/deploy/plugins
      - name: Set env TEST_DIRECTORY
        run: "if env.PRESTASHOP_VERSION == '1.6.1.24'; then\n    echo \"TEST_DIRECTORY=test/integration-tests/1.6.1.x\" >> \"$GITHUB_ENV\"\nelse\n    echo \"TEST_DIRECTORY=test/integration-tests/1.7.7.x\" >> \"$GITHUB_ENV\"\nfi  \t\n"
      - uses: actions/checkout@v1
        with:
          repository: AltaPay/plugin-prestashop
          ref: origin/cypress-test
          path: plugin-prestashop
      - name: Create Cypress fixture config json
        id: create-json-2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: config.json
          json: >-
            {"shopURL": "http://${{env.IP}}","adminURL":
            "http://${{env.IP}}/admin123","adminUsername":
            "${{secrets.CMS_ADMIN_EMAIL}}","adminPass":
            "${{secrets.SHOP_ADMIN_PASS}}"}
          dir: '${{env.TEST_DIRECTORY}}/cypress/fixtures/'
      - name: Install Cypress Dependencies
        run: npm i
        working-directory: '${{env.TEST_DIRECTORY}}'
      - name: Run Cypress tests
        run: ./node_modules/.bin/cypress run --config video=false
        working-directory: '${{env.TEST_DIRECTORY}}'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: './${{env.TEST_DIRECTORY}}/cypress/screenshots'
